# Generated by Django 4.0.2 on 2022-02-24 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='report_id',
            new_name='number',
        ),
    ]
