# Generated by Django 4.0.2 on 2022-02-11 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_timekeepingrecord_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='timekeepingrecord',
            name='employee_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payroll.employeereport'),
        ),
    ]
