# Generated by Django 4.0.2 on 2022-02-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_timekeepingrecord_employee_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeereport',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='jobgroup',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='timekeepingrecord',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
