# Generated by Django 4.0.2 on 2022-02-12 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_alter_employeereport_amount_paid_alter_jobgroup_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timekeepingrecord',
            name='employee_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.employeereport'),
        ),
    ]
