# Generated by Django 4.0.2 on 2022-02-12 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_alter_timekeepingrecord_employee_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeereport',
            name='report',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.CASCADE, to='payroll.report'),
            preserve_default=False,
        ),
    ]
