# Generated by Django 4.0.2 on 2022-02-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_alter_employeereport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeereport',
            name='report',
            field=models.ManyToManyField(null=True, to='payroll.Report'),
        ),
    ]
