# Generated by Django 4.0.2 on 2022-02-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_alter_employeereport_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeereport',
            name='report',
            field=models.ManyToManyField(to='payroll.Report'),
        ),
    ]
