# Generated by Django 4.0.2 on 2022-02-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_remove_employeereport_report_employeereport_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='id',
        ),
        migrations.AddField(
            model_name='report',
            name='report_id',
            field=models.IntegerField(default=69, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
