# Generated by Django 4.0.2 on 2022-02-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_remove_report_id_report_report_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeereport',
            name='report',
        ),
        migrations.AddField(
            model_name='employeereport',
            name='report',
            field=models.ManyToManyField(to='payroll.Report'),
        ),
    ]
